
services:

  c2server:
    build:
      context: ./c2server
      dockerfile: Dockerfile
    container_name: darkscry_c2server

    volumes:
      - "./keys/mykey.pem:${PRIVATE_KEY_PATH:-/etc/keys/priv.key}:ro"

    ports:
      - "${C2SERVER_PORT:-9100}:9100"
      - "1234:1234"
      - "876:876"

    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-}"
      PRIVATE_KEY_PATH: "${PRIVATE_KEY_PATH}"
      C2_SERVER_HOST: "${C2_SERVER_HOST}"
      C2_SERVER_PORT: "${C2_SERVER_PORT}"
      C2_SERVER_REDIS_DB: "${C2_SERVER_REDIS_DB}"

    command: >
      poetry run python test.py

    depends_on:
      - redis
    restart: unless-stopped

  
  django:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    container_name: darkscry_django

    ports:
      - "${DJANGO_PORT:-8000}:8000"

    volumes:
    - db_password:/run/secrets

    depends_on:
      - c2server
      - db
    restart: unless-stopped

    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-}"

      DJANGO_JWT_SECRET: "${DJANGO_JWT_SECRET}"
      DJANGO_JWT_REFRESH_SECRET: "${DJANGO_JWT_REFRESH_SECRET}"
      DJANGO_JWT_ALGORITHM: "${DJANGO_JWT_ALGORITHM:-HS256}"
      DJANGO_JWT_EXPIRE_SECONDS: "${DJANGO_JWT_EXPIRE_SECONDS:-360000}"
      DJANGO_JWT_REFRESH_EXPIRE_SECONDS: "${DJANGO_JWT_REFRESH_EXPIRE_SECONDS:-3240000}"

      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT:-5432}"

      C2_SERVER_HOST: "${C2_SERVER_HOST}"
      C2_SERVER_PORT: "${C2_SERVER_PORT}"

    command: >
      poetry run uvicorn DarkScryC2Managment.asgi:application --host 0.0.0.0 --port 8000

  
  redis:
    image: redis:7-alpine
    container_name: darkscry_redis
    ports:
      - "6379"
    restart: unless-stopped

  
  db:
    image: postgres:14-alpine
    container_name: darkscry_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password" 
    volumes:
      - darkscry_postgres_data:/var/lib/postgresql/data
      - db_password:/run/secrets
    restart: unless-stopped

  arqworker:
    build:
      context: .
      dockerfile: ./dockerfiles/arq.dockerfile
    container_name: darkscry_arqworker
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-}"
      REDIS_PORT: "6379"
      ARQ_REDIS_DB: "${ARQ_REDIS_DB:-4}"

      C2_SERVER_HOST: "${C2_SERVER_HOST}"
      C2_SERVER_PORT: "${C2_SERVER_PORT}"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: darkscry_frontend

    environment:
      NEXT_PUBLIC_DJANGO_API_URL_V2: "http://django:8000/api/v2"
      NEXT_PUBLIC_WS_URL: "ws://django:8000"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "nhCZTYUAgKUSc9MLxWKHq04DXnH0b5hDYFFZbmySMfsFAV9c3jGiF9pqiyw"

    ports:
      - "3000:3000"

    depends_on:
      - django

    restart: unless-stopped

volumes:
  darkscry_postgres_data:
  db_password:  
