
services:

  #################################################
  # 1) C2 Server
  #################################################
  c2server:
    build:
      context: ./c2server
      dockerfile: Dockerfile
    container_name: darkscry_c2server

    volumes:
      - "./keys/mykey.pem:${PRIVATE_KEY_PATH:-/etc/keys/priv.key}:ro"

    ports:
      - "${C2SERVER_PORT:-9100}:9100"
      - "1234:1234"
      - "876:876"

    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-}"
      PRIVATE_KEY_PATH: "${PRIVATE_KEY_PATH}"
      C2_SERVER_HOST: "${C2_SERVER_HOST}"
      C2_SERVER_PORT: "${C2_SERVER_PORT}"
      C2_SERVER_REDIS_DB: "${C2_SERVER_REDIS_DB}"

    command: >
      poetry run python test.py

    depends_on:
      - redis
    restart: unless-stopped

  #################################################
  # 2) Django
  #################################################
  django:
    build:
      context: .
      dockerfile: ./django/Dockerfile
    container_name: darkscry_django

    ports:
      - "${DJANGO_PORT:-8000}:8000"

    volumes:
    - db_password:/run/secrets

    depends_on:
      - c2server
      - db
    restart: unless-stopped

    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-}"

      DJANGO_JWT_SECRET: "${DJANGO_JWT_SECRET}"
      DJANGO_JWT_REFRESH_SECRET: "${DJANGO_JWT_REFRESH_SECRET}"
      DJANGO_JWT_ALGORITHM: "${DJANGO_JWT_ALGORITHM:-HS256}"
      DJANGO_JWT_EXPIRE_SECONDS: "${DJANGO_JWT_EXPIRE_SECONDS:-360000}"
      DJANGO_JWT_REFRESH_EXPIRE_SECONDS: "${DJANGO_JWT_REFRESH_EXPIRE_SECONDS:-3240000}"

      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT:-5432}"

      C2_SERVER_HOST: "${C2_SERVER_HOST}"
      C2_SERVER_PORT: "${C2_SERVER_PORT}"

    command: >
      poetry run uvicorn DarkScryC2Managment.asgi:application --host 0.0.0.0 --port 8000

  #################################################
  # 3) Redis
  #################################################
  redis:
    image: redis:7-alpine
    container_name: darkscry_redis
    ports:
      - "63790:6379"
    restart: unless-stopped

  #################################################
  # 4) Postgres DB
  #################################################
  db:
    image: postgres:14-alpine
    container_name: darkscry_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password" 
    volumes:
      - darkscry_postgres_data:/var/lib/postgresql/data
      - db_password:/run/secrets
    restart: unless-stopped

volumes:
  darkscry_postgres_data:
  db_password:  
