# Generated by Django 5.1.5 on 2025-01-16 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('AgentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('HostName', models.CharField(max_length=255)),
                ('Os', models.CharField(max_length=100)),
                ('LastTimeUpdate', models.DateTimeField(auto_now_add=True)),
                ('OnboardedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
