# Generated by Django 5.1.5 on 2025-01-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_agent_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='AgentId',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
